<a href="https://colab.research.google.com/github/Srourrzan/AI_refresher/blob/main/PyTorch_fundemantals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.rand(5, 3);
print(x);

tensor([[0.6391, 0.4088, 0.6920],
        [0.6977, 0.9663, 0.6856],
        [0.5340, 0.1997, 0.8696],
        [0.2348, 0.9755, 0.7849],
        [0.7026, 0.2091, 0.0626]])


In [ ]:
if (torch.cuda.is_available()):
  print("cuda is avaiblable");
else:
  print("cuda is not available");

cuda is not available


In [ ]:
import numpy as np;
from sklearn.datasets import load_iris;
from sklearn.linear_model import Perceptron;

In [ ]:
iris = load_iris(as_frame=True);
X = iris.data[["petal length (cm)", "petal width (cm)"]].values;
y = (iris.target == 0);

In [ ]:
per_clf = Perceptron(random_state=42);
per_clf.fit(X, y);

In [ ]:
X_new = [[2, 0.5], [3, 1]];
y_pred = per_clf.predict(X_new);

In [ ]:
print(f"y_pred = {y_pred}");

y_pred = [ True False]


In [ ]:
x: int = 1;

----------------------------------------------------------------------

In [ ]:
from sklearn.pipeline import make_pipeline;
from sklearn.metrics import mean_squared_error;
from sklearn.neural_network import MLPRegressor;
from sklearn.preprocessing import StandardScaler;
from sklearn.model_selection import train_test_split;
from sklearn.datasets import fetch_california_housing;

In [ ]:
housing = fetch_california_housing();
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target, random_state=42);
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, random_state=42);
mlp_reg = MLPRegressor(hidden_layer_sizes=[50, 50, 50], random_state=42);

In [ ]:
pipeline = make_pipeline(StandardScaler(), mlp_reg);

In [ ]:
pipeline.fit(X_train, y_train);

In [ ]:
import numpy as np;
from numpy import ndarray;
mse: float;
rmse: float;
y_pred: ndarray;

y_pred = pipeline.predict(X_valid);
mse = mean_squared_error(y_valid, y_pred);
rmse = np.sqrt(mse);

In [ ]:
print(f"rmse = {rmse}");

rmse = 0.5053326657968684


-------------------------------------------------------------------------

In [ ]:
import torch;
import numpy as np;

In [ ]:
data: np.ndarray;
x_data: torch.Tensor;

data = [[1, 2], [3, 4]];
x_data = torch.tensor(data);

In [ ]:
np_array: np.ndarray = np.array(data);
x_np: torch.Tensor = torch.from_numpy(np_array);
print(f"x_np = {x_np}");

x_np = tensor([[1, 2],
        [3, 4]])


In [ ]:
x_ones: torch.tensor;
x_rand: torch.tensor;

x_ones = torch.ones_like(x_data);
print(f"Ones Tesnor: \n{x_ones} \n");
x_rand = torch.rand_like(x_data, dtype=torch.float);
print(f"Random Tensor: \n {x_rand}\n");

Ones Tesnor: 
tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9526, 0.3274],
        [0.8058, 0.9350]])



In [ ]:
shape: tuple;
rand_tensor: torch.tensor;
ones_tensor: torch.tensor;
zeros_tensor: torch.zeros;

shape = (2, 3,);
rand_tensor = torch.rand(shape);
ones_tensor = torch.ones(shape);
zeros_tensor = torch.zeros(shape);
print(f"Random Tensror: \n {rand_tensor} \n");
print(f"Ones Tensor: \n {ones_tensor} \n");
print(f"Zeros Tensor: \n {zeros_tensor} \n");

Random Tensror: 
 tensor([0.6971, 0.3312]) 

Ones Tensor: 
 tensor([1., 1.]) 

Zeros Tensor: 
 tensor([0., 0.]) 



In [ ]:
tensor = torch.rand(3, 4);

print(f"Shape of tensor: {tensor.shape}");
print(f"Datatype of tensor: {tensor.dtype}");
print(f"Device tensor is stored on: {tensor.device}");

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


-----------------------------------------------------------------------------------------------------

In [ ]:
import torch;
import numpy as np;

In [ ]:
tensor: torch.tensor;

tensor = torch.rand(3, 4);
if torch.cuda.is_available():
  tensor = tensor.to('cuda');
  print(f"Device tensor is stored on: {tensor.device}");

Device tensor is stored on: cuda:0


In [ ]:
tensor = torch.ones(4, 4);
tensor[:, 1] = 0;
print(tensor);

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
t1: torch.tensor = torch.cat([tensor, tensor, tensor], dim=1);
print(t1);

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n");
print(f"tensor * tensor \n {tensor * tensor}");

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n");
print(f"tensor @ tensor.T \n {tensor @ tensor.T}");

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
